In [1]:

# https://www.kaggle.com/shayanfazeli/heartbeat   # data set 

# Importing libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt # plotting
import os
import sklearn
from keras.models import Sequential
from keras.layers import Flatten, Dense, Dropout, BatchNormalization, AveragePooling2D
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier



Using TensorFlow backend.


In [2]:
# reading csv file  

test=pd.read_csv("mitbih_test.csv",header=None) 
train=pd.read_csv("mitbih_train.csv",header=None) 
#Classes: ['N': 0, 'S': 1, 'V': 2, 'F': 3, 'Q': 4]
# N- normal, S-supraventricular, V-ventricular, F-fusion, Q- unknown

In [3]:
print("Type\tCount")
print((train[187]).value_counts())

print("train shape : ",train.shape)
print("test shape : ",test.shape)


Type	Count
0.0    72471
4.0     6431
2.0     5788
1.0     2223
3.0      641
Name: 187, dtype: int64
train shape :  (87554, 188)
test shape :  (21892, 188)


In [4]:
print('Count of all classes in training dataset')
print("Type\tCount")
print((train[187]).value_counts())

print('*************************************')

print('Count of all classes in test dataset')
print("Type\tCount")
print((test[187]).value_counts())

Count of all classes in training dataset
Type	Count
0.0    72471
4.0     6431
2.0     5788
1.0     2223
3.0      641
Name: 187, dtype: int64
*************************************
Count of all classes in test dataset
Type	Count
0.0    18118
4.0     1608
2.0     1448
1.0      556
3.0      162
Name: 187, dtype: int64


In [5]:
print("train shape : ",train.shape)
print("test shape : ",test.shape)

feature_train=train.iloc[:,0:187] 
print("feature_train shape : ",feature_train.shape)

labels_train=train.iloc[:,187] 
print("labels_train shape : ",labels_train.shape)

feature_test=test.iloc[:,0:187] 
print("feature_test shape : ",feature_test.shape)

labels_test=test.iloc[:,187] 
print("labels_test shape : ",labels_test.shape)
      


train shape :  (87554, 188)
test shape :  (21892, 188)
feature_train shape :  (87554, 187)
labels_train shape :  (87554,)
feature_test shape :  (21892, 187)
labels_test shape :  (21892,)


In [6]:
from sklearn.preprocessing import StandardScaler
standardized_training_data=StandardScaler().fit_transform(feature_train)
feature_train=standardized_training_data

standardized_test_data=StandardScaler().fit_transform(feature_test)
feature_test=standardized_test_data

In [7]:
x_train1=feature_train
x_test1=feature_test
y_train1=labels_train
y_test1=labels_test

In [8]:
# Logistic Regression
a_lr=LogisticRegression()
a_lr.fit(x_train1,y_train1)
y_pred_lr=a_lr.predict(x_test1)

cm_lr=confusion_matrix(y_test1,y_pred_lr)
print(cm_lr)
print("********************************")

report_lr=classification_report(y_test1,y_pred_lr)
print(report_lr)

print("********************************")

Precision_lr= precision_score(y_test1, y_pred_lr,average='weighted')      
print('Precision of lr is : {0}'.format(Precision_lr))

Recall_lr= recall_score(y_test1, y_pred_lr,average='weighted')
print('Recall of lr is : {0}'.format(Recall_lr))

F1_score_lr= f1_score(y_test1, y_pred_lr,average='weighted')
print('F1_score of lr is : {0}'.format(F1_score_lr))

Accuracy_lr=accuracy_score(y_test1, y_pred_lr)
print("Accuracy of lr is : {0}".format(Accuracy_lr))


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[17867    17   208     2    24]
 [  408   121    27     0     0]
 [  935    12   470     4    27]
 [  129     0    10    23     0]
 [  196     2    15     0  1395]]
********************************
              precision    recall  f1-score   support

         0.0       0.91      0.99      0.95     18118
         1.0       0.80      0.22      0.34       556
         2.0       0.64      0.32      0.43      1448
         3.0       0.79      0.14      0.24       162
         4.0       0.96      0.87      0.91      1608

    accuracy                           0.91     21892
   macro avg       0.82      0.51      0.58     21892
weighted avg       0.90      0.91      0.89     21892

********************************
Precision of lr is : 0.8964753854556261
Recall of lr is : 0.9079115658688105
F1_score of lr is : 0.8915406648155909
Accuracy of lr is : 0.9079115658688105


In [9]:
# [[17867    17   208     2    24]
#  [  408   121    27     0     0]
#  [  935    12   470     4    27]
#  [  129     0    10    23     0]
#  [  196     2    15     0  1395]]
# ********************************
#              precision    recall  f1-score   support

#         0.0       0.91      0.99      0.95     18118
#         1.0       0.80      0.22      0.34       556
#         2.0       0.64      0.32      0.43      1448
#         3.0       0.79      0.14      0.24       162
#         4.0       0.96      0.87      0.91      1608

#    accuracy                           0.91     21892
#   macro avg       0.82      0.51      0.58     21892
# weighted avg       0.90      0.91      0.89     21892

# ********************************
# Precision of lr is : 0.8964753854556261
# Recall of lr is : 0.9079115658688105
# F1_score of lr is : 0.8915406648155909
# Accuracy of lr is : 0.9079115658688105